import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
            <header>
                <Link href="/">
                        <div>Home</div>
                </Link>
                <Link href="/carReservation">
                        <div>Расписание</div>
                </Link>
                <Link href="/login">
                        <div>Войти</div>
                </Link>
            </header>
            <main>
                <div className='content'>
                    {children}
                </div>
            </main>
        </body>
    </html>
  )
}
